https://app.houseofcb.com/cadie-black-satin-corset-top: ''
https://app.houseofcb.com/gaia-black-lace-corset-midi-dress: ''
https://bondisands.com/products/self-tanning-foam-light-medium: https://bondisands.com/cdn/shop/files/DESKTOP-WEB-PDP-SPEC-PNG-PRODUCT-IMAGE-LIGHT-MEDIUM-SELF-TANNING-FOAM-988x1296px.png?v=1784700281
https://jenny-bird.com/products/dane-collar: https://jenny-bird.com/cdn/shop/files/DaneCollar-Gold_-1.jpg?v=1712608798&width=2048
https://jenny-bird.com/products/florence-earrings-gold: https://jenny-bird.com/cdn/shop/files/FlorenceEarrings-Gold-1_08b862d3-e5df-4e71-993c-8e6834526afc.jpg?v=1765214904&width=2048
https://jenny-bird.com/products/ola-arm-cuff-gold: https://jenny-bird.com/cdn/shop/files/OlaArmCuff-HPG-1.jpg?v=1776888188&width=2048
https://us.nuxe.com/products/huile-prodigieuse-or-50-ml: https://us.nuxe.com/cdn/shop/files/3264680009785-VN043002-VIEW_2-HP-OR_50ML_PACKSHOT_2000x2000_544232b3-1219-4e0a-b42b-14258cbdc593.jpg?v=1718290572&width=2048
https://us.sandro-paris.com/en/p/cardigan-with-pearl-flower-collar/SFPCA01529_20.html: https://us.sandro-paris.com/on/demandware.static/-/Sites-master-catalog/default/dwb9c56ddb/images/hi-res/Sandro_SFPCA01529-20_F_1.jpg
https://www.analuisa.com/products/statement-ring-remi: https://cdn.shopify.com/s/files/1/2579/7674/files/Ana-Luisa-Jewelry-Rings-Statement-Ring-Remi-Gold_2d531e98-5225-44e1-82bf-64812b7a747d.jpg
https://www.caminyc.com/products/the-racer-charmeuse-black: https://www.caminyc.com/cdn/shop/files/2025_Cami-Aug50299copy_e6ecdcb9-d0b8-421d-a748-7a390fd44e77.jpg?v=1755110343
https://www.caminyc.com/products/tully-lace-blouse-f26-t08-black: https://www.caminyc.com/cdn/shop/files/17_49db4690-6f53-441b-97af-951ff7171617.png?v=1789569103
https://www.corneliajames.com/en-us/products/hermione-duchess-satin-glove: https://www.corneliajames.com/cdn/shop/files/hermione-satin-opera-gloves-2.jpg?v=1786986188
https://www.ettika.com/products/blissful-crystal-body-chain-in-gold: https://www.ettika.com/cdn/shop/files/Ettika662a6afaf36634662a6afaf385d.28397733662a6afaf385d.jpg?v=1762442266&width=1200
https://www.freepeople.com/shop/for-love-and-lemons-gilded-lace-bustier/: ''
https://www.freepeople.com/shop/loved-you-first-lace-cami/: ''
https://www.freepeople.com/shop/sam-lace-button-down-top/: ''
https://www.jwpei.com/products/mini-abacus-hs: https://www.jwpei.com/cdn/shop/files/2T33-1ArtificalCrystalMiniTopHandleBag-Black_1_9a0fbd9b-9cbe-4a44-a408-1a261cd095fa.jpg?v=1784716428
https://www.narscosmetics.com/USA/explicit-lipstick/999NAC0000221.html: https://www.narscosmetics.com/dw/image/v2/BBSK_PRD/on/demandware.static/-/Sites-itemmaster_NARS/default/dw258be086/2026/February/ExplicitLipstick/0194251171746_1.jpg?sw=856&sh=750&sm=fit
https://www.nordstrom.com/s/ellie-long-sleeve-lace-bodysuit/8890587: ''
https://www.nordstrom.com/s/embroidered-lace-long-sleeve-gown/7920072: ''
https://www.nordstrom.com/s/lace-trim-sweetheart-neck-corset-top/7583066: ''
https://www.sephora.com/product/beach-skin-shimmering-body-oil-P522415: ''
https://www.sephora.com/product/benetint-cheek-lip-stain-P1272: ''
https://www.sephora.com/product/dolce-glow-acqua-dark-hydrating-self-tanning-face-mist-P521665: ''
https://www.sephora.com/product/glowmotions-P442821: ''
https://www.sephora.com/product/instant-golden-glow-with-almond-shimmering-body-oil-P516738: ''
https://www.sephora.com/product/n-176-32-hydrating-gradual-self-tanning-lotion-in-santal-P512376: ''
https://www.sephora.com/product/range-beauty-bali-face-body-glow-oil-P513665: ''
https://www.sephora.com/product/self-tan-classic-bronzing-mousse-P407450: ''
https://www.sephora.com/product/self-tan-face-drops-P516435: ''
https://www.sephora.com/product/shimmer-body-oil-P446344: ''
https://www.simons.ca/en/women-clothing/blazers-vests/crest-buttons-stretch-crepe-blazer--9718-229830: ''
https://www.simons.ca/en/women-clothing/camis/night-out/lace-trim-satiny-cami--12709-232649: ''
https://www.simons.ca/en/women-clothing/skirts/midi/satiny-midi-skirt--11796-2933863: ''
https://www.stevemadden.com/products/larina-red-satin: https://www.stevemadden.com/cdn/shop/files/STEVEMADDEN_SHOES_LARINA_RED-SATIN.jpg?v=1753461715
https://www.ulta.com/p/instant-glow-face-body-bronzer-makeup-pimprod2031120?sku=2592029: https://media.ulta.com/i/ulta/2592029?w=500&h=500
https://www.ulta.com/p/macximal-silky-matte-lipstick-pimprod2043558?sku=2621398: https://media.ulta.com/i/ulta/2621398?w=500&h=500
https://www.ulta.com/p/superstay-matte-ink-liquid-lipstick-xlsImpprod16211185?sku=2510218: https://media.ulta.com/i/ulta/2510218?w=500&h=500
